# File: netlify.toml

[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Add these three lines at the end
[[plugins]]
package = "@netlify/plugin-functions-install-core"